### ISSUE TITLE
Allow to run pipelines defined in yaml

### ISSUE THREAD

**Issue by licaonfee** [licaonfee/ratchet#5]
Add a way to define a pipeline via yaml files 

Proposal
```yaml
---
name: "Pipeline name"
cron: "* * * * * *" # maybe another processor
steps:
- SQLReader:
    driver: "mysql"
    conn: "user:password@tcp(databasehost:3306)/database"
    query: >
        SELECT
            id,
            count(*) as count
        FROM
            my_table
        GROUP BY id
- CSVTransform:
    writeHeader: true
    header: ["id", "count"]
- FtpWriter:
    host: "remotehost:21"
    user: ftpuser
    password: ftppassword1213
    filename: 'my_reports/report_{{ .hostname }}_{{ .time.Format "2006-01-02" }}.csv'
```
